Repository sdbx/Utils, pull requests merged in 2024-06, with the labels that each got.

#1 hd
  hd/.gitignore
  hd/README.md
  hd/hd.c
  hd/hd.cpp
  hd/hd.js
  hd/hd.rs
  hd/hd.test.js
Labels: enhancement

#4 Add C++ implementation for hhss.
  .gitignore
  hhss/README.md
  hhss/hhss_cpp/.clang-format
  hhss/hhss_cpp/CMakeLists.txt
  hhss/hhss_cpp/CMakePresets.json
  hhss/hhss_cpp/generator.cpp
  hhss/hhss_cpp/generator.h
  hhss/hhss_cpp/hhss_cpp.cpp
  hhss/hhss_cpp/hhss_cpp.h
  hhss/hhss_cpp/random_formatting_map.cpp
  hhss/hhss_cpp/random_formatting_map.h
  hhss/hsr.dat
  hhss/usr.dat
Labels: enhancement

#5 [Quality] Reorganize files.
  btn/c/.gitignore
  btn/c/Makefile
  btn/c/buntang.c
  btn/haskell/buntang.hs
  btn/python/btn.py
  hd/c/.gitignore
  hd/c/hd.c
  hd/cpp/hd.cpp
  hd/haskell/hd.hs
  hd/javascript/hd.js
  hd/rust/hd.rs
  hd/tests/hd.test.js
  hhss/c/.gitignore
  hhss/c/Makefile
  hhss/c/hutsori.c
  hhss/cpp/.clang-format
  hhss/cpp/CMakeLists.txt
  hhss/cpp/CMakePresets.json
  hhss/cpp/generator.cpp
  hhss/cpp/generator.h
  hhss/cpp/hhss_cpp.cpp
  hhss/cpp/hhss_cpp.h
  hhss/cpp/random_formatting_map.cpp
  hhss/cpp/random_formatting_map.h
  hhss/haskell/hutsori.hs
  nsy/c/.gitignore
  nsy/c/Makefile
  nsy/c/noisy.c
  nsy/haskell/noisy.hs
  nsy/hip/.clang-format
  nsy/hip/Makefile
  nsy/hip/msvc_defines.h
  nsy/hip/nsy_hip.cu
  nsy/hip/nsy_hip.sln
  nsy/hip/nsy_hip.vcxproj
  nsy/hip/nsy_hip.vcxproj.filters
  nsy/hip/nsy_hip.vcxproj.user
  nsy/python/nsy.py
  yandere/c/yandere.c
  yandere/haskell/yandere.hs
Labels: quality, blocker

#7 [Docs] Modify respective README.md
  btn/README.md
  hd/README.md
  hhss/README.md
  nsy/README.md
  yandere/README.md
Labels: documentation

#8 [Docs] Modify readme
  btn/README.md
  nsy/README.md
Labels: documentation

#10 [Docs] Proposal: yandere specification
  yandere/SPECIFICATION.md
Labels: documentation

#9 [Docs] Proposal: btn specification
  btn/SPECIFICATION.md
Labels: documentation

#11 [Docs] Proposal: nsy specification
  nsy/SPECIFICATION.md
Labels: documentation

#13 [Docs] Proposal: hd specification
  hd/SPECIFICATION.md
Labels: documentation

#17 [Enhancement] New programs: test with test_maker
  test/.gitignore
  test/.test/btn.test
  test/.test/hd.test
  test/.test/nsy.test
  test/DESIGN.md
  test/test.c
  test/test_maker.c
Labels: blocker, ci

#18 [CI] Add testing CI.
  .github/workflows/btn_c.yml
  .github/workflows/btn_haskell.yml
  .github/workflows/btn_python.yml
  .github/workflows/hd_c.yml
  .github/workflows/hd_cpp.yml
  .github/workflows/hd_haskell.yml
  .github/workflows/hd_javascript.yml
  .github/workflows/hd_rust.yml
  .github/workflows/nsy_c.yml
  .github/workflows/nsy_haskell.yml
  .github/workflows/nsy_python.yml
Labels: ci

#25 [Docs] Add readme files
  README.md
  test/README.md
Labels: documentation

#22 [Documentation] Update hhss-related files
  hhss/SPECIFICATION.md
  hhss/c/hhss.c
  hhss/hsr.dat
Labels: documentation

#26 [Feature] Add more delimiters for noisy C implementation: period, ellipsis, plus, comma, heart
  nsy/c/nsy.c
Labels: enhancement

#28 [Feature] Neat output of test program
  test/test.c
Labels: enhancement

#21 [Fix] Standard-conforming implementations of btn & nsy in python
  btn/python/btn.py
  nsy/python/nsy.py
Labels: bug

#30 [CI] Fix GitHub CI.
  .github/workflows/pr_haskell.yml
  .github/workflows/pr_javascript.yml
  .github/workflows/push_c.yml
  .github/workflows/push_cpp.yml
  .github/workflows/push_haskell.yml
  .github/workflows/push_javascript.yml
  .github/workflows/push_python.yml
  .github/workflows/push_rust.yml
Labels: ci

#31 [Docs] Update readme
  README.md
Labels: documentation

#33 [Fix] Modify python implementations of btn and nsy
  btn/python/btn.py
  nsy/python/nsy.py
Labels: bug

#32 [Fix] Modify test and test_maker
  test/test.c
  test/test_maker.c
Labels: bug, enhancement

#34 [Quality] Organize haskell-related files
  .github/workflows/pr_haskell.yml
  .github/workflows/push_haskell.yml
  btn/haskell/.gitignore
  btn/haskell/btn.hs
  hd/haskell/.gitignore
  hhss/haskell/.gitignore
  hhss/haskell/hhss.hs
  nsy/haskell/.gitignore
  nsy/haskell/nsy.hs
  yandere/haskell/.gitignore
Labels: quality, ci

#35 [Docs] Elaborate specs
  btn/SPECIFICATION.md
  hd/SPECIFICATION.md
  nsy/SPECIFICATION.md
Labels: documentation

#37 [Fix] Modify btn.c
  btn/c/btn.c
Labels: bug

#38 [Enhancement] New program: nsy2!
  README.md
  nsy2/SPECIFICATION.md
  nsy2/c/.gitignore
  nsy2/c/Makefile
  nsy2/c/nsy2.c
Labels: enhancement

#39 [Fix] test.c
  test/test.c
Labels: enhancement

#40 [Docs] Fix ~/readme.md
  README.md
Labels: documentation

#41 [CI] Fix Haskell CI.
  .github/workflows/pr_haskell.yml
Labels: ci

#43 [Fix] LET THERE BE INLINE
  nsy/c/nsy.c
  nsy2/c/nsy2.c
Labels: enhancement

#42 [Enhancement] Support multiple expected outputs in the test program
  test/.test/btn.test
  test/.test/hd.test
  test/.test/nsy.test
  test/README.md
  test/test.c
  test/test.h
  test/test.macros.h
  test/test.types.h
  test/test_maker.c
  test/test_maker.h
Labels: enhancement
